from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from card_scanner.active_price_comparison import EXACT_MATCH, build_active_price_comparisons


def _load(path: str) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _key(group: dict[str, Any]) -> str:
    return str(group.get("comparison_key") or "")


def _listing_key(row: dict[str, Any]) -> tuple[str, str]:
    return (
        str(row.get("source") or "").casefold(),
        str(row.get("external_id") or ""),
    )


def merge_additive_nfl_exact(
    production: dict[str, Any], staging: dict[str, Any]
) -> dict[str, Any]:
    """Add strict staged NFL exact groups without deleting production groups.

    Staged groups are generated by the same strict structured matcher and title
    rejection guard used elsewhere. Existing production groups are copied
    verbatim and always win on key collisions.
    """
    production_groups = list(production.get("comparison_groups") or production.get("groups") or [])
    production_keys = {_key(group) for group in production_groups if _key(group)}

    staged = build_active_price_comparisons(list(staging.get("market_cards") or []))
    staged_exact = [
        group
        for group in staged.get("groups") or []
        if group.get("comparison_type") == EXACT_MATCH
        and int(group.get("store_count") or 0) >= 2
        and _key(group)
    ]
    additions = [group for group in staged_exact if _key(group) not in production_keys]

    final_groups = [*production_groups, *additions]

    cards_by_key: dict[tuple[str, str], dict[str, Any]] = {}
    for card in production.get("market_cards") or []:
        key = _listing_key(card)
        if all(key):
            cards_by_key[key] = card

    wanted_addition_listings = {
        _listing_key(listing)
        for group in additions
        for listing in group.get("listings") or []
        if all(_listing_key(listing))
    }
    for card in staging.get("market_cards") or []:
        key = _listing_key(card)
        if key in wanted_addition_listings and key not in cards_by_key:
            cards_by_key[key] = card

    production_listing_count = sum(
        int(group.get("listing_count") or len(group.get("listings") or []))
        for group in production_groups
    )
    added_listing_count = sum(
        int(group.get("listing_count") or len(group.get("listings") or []))
        for group in additions
    )

    output = dict(production)
    output["feed_type"] = "EXACT_CARD_STORE_COMPARISON_ONLY"
    governance = dict(output.get("governance") or {})
    governance.update(
        {
            "exact_card_only": True,
            "staged_nfl_additive_promotion": True,
            "existing_production_groups_preserved": True,
            "production_group_deletion_allowed": False,
            "strict_exact_matcher_reused_for_nfl": True,
            "title_discriminator_guard_reused_for_nfl": True,
        }
    )
    output["governance"] = governance
    output["market_cards"] = list(cards_by_key.values())
    output["comparison_groups"] = final_groups

    metrics = dict(output.get("metrics") or {})
    metrics.update(
        {
            "production_groups_before_nfl_merge": len(production_groups),
            "production_listings_before_nfl_merge": production_listing_count,
            "staged_nfl_exact_groups_seen": len(staged_exact),
            "staged_nfl_groups_added": len(additions),
            "staged_nfl_listings_added": added_listing_count,
            "exact_comparison_groups": len(final_groups),
            "exact_comparison_listings": production_listing_count + added_listing_count,
            "production_groups_lost": 0,
        }
    )
    output["metrics"] = metrics
    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Add strict NFL staging exact groups to production without deleting existing comparisons."
    )
    parser.add_argument("--production", default="docs/comparison.json")
    parser.add_argument("--staging", default="docs/nfl_inventory.json")
    parser.add_argument("--output", default="docs/comparison.json")
    args = parser.parse_args()

    merged = merge_additive_nfl_exact(_load(args.production), _load(args.staging))
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(merged, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    metrics = merged["metrics"]
    print("NFL_EXACT_ADDITIVE_PROMOTION=PASS")
    print(f"PRODUCTION_GROUPS_BEFORE={metrics['production_groups_before_nfl_merge']}")
    print(f"STAGED_NFL_EXACT_GROUPS_SEEN={metrics['staged_nfl_exact_groups_seen']}")
    print(f"STAGED_NFL_GROUPS_ADDED={metrics['staged_nfl_groups_added']}")
    print(f"STAGED_NFL_LISTINGS_ADDED={metrics['staged_nfl_listings_added']}")
    print(f"FINAL_EXACT_GROUPS={metrics['exact_comparison_groups']}")
    print(f"FINAL_EXACT_LISTINGS={metrics['exact_comparison_listings']}")
    print("PRODUCTION_GROUPS_LOST=0")
    print(f"OUTPUT={output.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
